INFO flwr 2023-12-19 17:04:25,422 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2023-12-19 17:04:25,466 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2023-12-19 17:04:25,466 | server.py:86 | Initializing global parameters
INFO flwr 2023-12-19 17:04:25,466 | server.py:273 | Requesting initial parameters from one random client
server booted up. starting clients...
INFO flwr 2023-12-19 17:05:42,410 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2023-12-19 17:05:42,418 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-12-19 17:05:42,419 | server.py:88 | Evaluating initial parameters
DEBUG flwr 2023-12-19 17:05:42,412 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,412 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:42,415 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:42,444 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,446 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,446 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:42,449 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:42,483 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,486 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,486 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:42,489 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:42,503 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,505 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,505 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:42,508 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:42,521 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,523 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,523 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:42,526 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:42,567 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,569 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,569 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:42,589 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,591 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,591 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:42,602 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,604 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,604 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:42,606 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:42,622 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,624 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,625 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:42,694 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,697 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,697 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:42,700 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:42,719 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,721 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,721 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:42,773 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,775 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,775 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:42,784 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,787 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,787 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:42,789 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:42,803 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,806 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,806 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:42,820 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,823 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,823 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:42,825 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:42,830 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,832 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,832 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:42,834 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:42,914 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:42,916 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:42,916 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:42,919 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:43,377 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:43,379 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:43,379 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:43,385 | server.py:91 | initial parameters (loss, other metrics): 2.3086775743484496, {'accuracy': 0.1079}
INFO flwr 2023-12-19 17:05:43,385 | server.py:101 | FL starting
INFO flwr 2023-12-19 17:05:43,392 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:43,395 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:43,395 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:43,818 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:43,820 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:43,820 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:43,822 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,081 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,084 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,084 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,087 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,088 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,090 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,090 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:44,164 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,167 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,167 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:44,434 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,437 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,437 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,440 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,542 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,545 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,545 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:44,565 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,568 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,568 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,571 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,654 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,656 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,656 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,658 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,714 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,718 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,718 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,721 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,723 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,726 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,726 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:44,741 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,743 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,743 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,746 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,758 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,760 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,760 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,762 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,765 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,767 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,767 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,770 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,794 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,796 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,796 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:44,858 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,861 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,861 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,863 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,864 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,866 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,866 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:44,868 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,870 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,871 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,871 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,871 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,873 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,873 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:44,883 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,885 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,885 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,889 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,901 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,903 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,903 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,906 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,916 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,918 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,918 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:44,936 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,938 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,938 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:44,942 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:44,946 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:44,948 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:44,948 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:45,003 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:45,005 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:45,005 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:45,015 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:45,017 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:45,017 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:45,021 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:45,040 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:45,043 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:45,043 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:45,045 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:45,046 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-12-19 17:05:45,047 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:45,047 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:45,050 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:45,062 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2023-12-19 17:05:45,064 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:45,065 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:45,065 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:45,066 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:45,066 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-19 17:05:45,069 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:45,069 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 17:05:45,071 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 17:05:45,073 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:45,073 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:45,074 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:05:45,074 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 17:05:45,076 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-12-19 17:05:45,077 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-12-19 17:06:02,571 | connection.py:113 | gRPC channel closed
booting up client 23
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
booting up client 21
DEBUG flwr 2023-12-19 17:06:02,592 | connection.py:113 | gRPC channel closed
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
DEBUG flwr 2023-12-19 17:06:02,625 | connection.py:113 | gRPC channel closed
booting up client 8
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: connection attempt timed out before receiving SETTINGS frame"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: connection attempt timed out before receiving SETTINGS frame {created_time:"2023-12-19T17:06:02.624633437+01:00", grpc_status:14}"
>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: connection attempt timed out before receiving SETTINGS frame"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: connection attempt timed out before receiving SETTINGS frame {grpc_status:14, created_time:"2023-12-19T17:06:02.591517101+01:00"}"
>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: connection attempt timed out before receiving SETTINGS frame"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: connection attempt timed out before receiving SETTINGS frame {grpc_status:14, created_time:"2023-12-19T17:06:02.569900055+01:00"}"
>
DEBUG flwr 2023-12-19 17:06:02,723 | connection.py:113 | gRPC channel closed
booting up client 43
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: connection attempt timed out before receiving SETTINGS frame"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: connection attempt timed out before receiving SETTINGS frame {created_time:"2023-12-19T17:06:02.722119213+01:00", grpc_status:14}"
>
DEBUG flwr 2023-12-19 17:06:02,776 | connection.py:113 | gRPC channel closed
booting up client 5
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: connection attempt timed out before receiving SETTINGS frame"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: connection attempt timed out before receiving SETTINGS frame {grpc_status:14, created_time:"2023-12-19T17:06:02.775247042+01:00"}"
>
DEBUG flwr 2023-12-19 17:06:02,807 | connection.py:113 | gRPC channel closed
booting up client 6
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: connection attempt timed out before receiving SETTINGS frame"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: connection attempt timed out before receiving SETTINGS frame {created_time:"2023-12-19T17:06:02.806304288+01:00", grpc_status:14}"
>
srun: error: gpu08: tasks 5-6,8,21,23,43: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9202551.1
slurmstepd: error: *** STEP 9202551.1 ON gpu08 CANCELLED AT 2023-12-19T17:06:03 ***
srun: error: gpu08: tasks 0-4,7,9-20,22,24-42,44-49: Terminated
srun: Force Terminated StepId=9202551.1
