INFO flwr 2024-01-18 11:20:34,691 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2024-01-18 11:20:34,826 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2024-01-18 11:20:34,826 | server.py:86 | Initializing global parameters
INFO flwr 2024-01-18 11:20:34,826 | server.py:273 | Requesting initial parameters from one random client
server booted up. starting clients...
INFO flwr 2024-01-18 11:21:34,164 | server.py:277 | Received initial parameters from one random client
INFO flwr 2024-01-18 11:21:34,165 | server.py:88 | Evaluating initial parameters
INFO flwr 2024-01-18 11:21:36,833 | server.py:91 | initial parameters (loss, other metrics): 2.3059193639037887, {'accuracy': 0.0889}
INFO flwr 2024-01-18 11:21:36,833 | server.py:101 | FL starting
INFO flwr 2024-01-18 11:21:38,215 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,217 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,218 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,221 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:38,415 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,417 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,417 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,421 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:38,596 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,600 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,601 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,605 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:38,622 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,625 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,625 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,628 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:38,764 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,767 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,768 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2024-01-18 11:21:38,770 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,773 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-18 11:21:38,774 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,774 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,778 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:38,783 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2024-01-18 11:21:38,786 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,787 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,787 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,789 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,789 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,790 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-18 11:21:38,793 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:38,799 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,801 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,801 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,805 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:38,805 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,807 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,807 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,811 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-18 11:29:38,816 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:29:39,020 | connection.py:113 | gRPC channel closed
booting up client 6
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-01-18T11:29:38.81631296+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
srun: error: awi22: task 6: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9232942.1
slurmstepd: error: *** STEP 9232942.1 ON awi22 CANCELLED AT 2024-01-18T11:29:39 ***
srun: error: awi22: tasks 0-5,7-9: Terminated
srun: Force Terminated StepId=9232942.1
