INFO flwr 2024-01-18 11:20:34,693 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2024-01-18 11:20:34,831 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2024-01-18 11:20:34,831 | server.py:86 | Initializing global parameters
INFO flwr 2024-01-18 11:20:34,831 | server.py:273 | Requesting initial parameters from one random client
server booted up. starting clients...
INFO flwr 2024-01-18 11:21:22,068 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:22,070 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:22,070 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:22,074 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:23,643 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:23,645 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:23,646 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:23,649 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:23,911 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:23,913 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:23,913 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:23,916 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:23,925 | server.py:277 | Received initial parameters from one random client
INFO flwr 2024-01-18 11:21:23,927 | server.py:88 | Evaluating initial parameters
INFO flwr 2024-01-18 11:21:26,564 | server.py:91 | initial parameters (loss, other metrics): 2.311350382881973, {'accuracy': 0.1009}
INFO flwr 2024-01-18 11:21:26,565 | server.py:101 | FL starting
INFO flwr 2024-01-18 11:21:34,148 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:34,150 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:34,151 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:34,154 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:36,222 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:36,224 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:36,224 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:36,227 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:37,059 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:37,061 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:37,061 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:37,065 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:38,630 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,634 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,634 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,639 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:38,641 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,644 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,644 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,648 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:38,728 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,731 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,731 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,735 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:38,740 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:38,742 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:38,743 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:38,746 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-18 11:21:38,747 | server.py:218 | fit_round 1: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-01-18 11:22:01,910 | server.py:232 | fit_round 1 received 10 results and 0 failures
WARNING flwr 2024-01-18 11:22:04,331 | qfedavg.py:237 | No fit_metrics_aggregation_fn provided
INFO flwr 2024-01-18 11:22:06,720 | server.py:119 | fit progress: (1, 2.298511052823828, {'accuracy': 0.1035}, 40.15490478416905)
INFO flwr 2024-01-18 11:22:06,720 | server.py:166 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2024-01-18 11:22:06,723 | server.py:218 | fit_round 2: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:22:28,347 | server.py:232 | fit_round 2 received 13 results and 0 failures
INFO flwr 2024-01-18 11:22:33,137 | server.py:119 | fit progress: (2, 2.281895405010348, {'accuracy': 0.1921}, 66.57172834035009)
INFO flwr 2024-01-18 11:22:33,137 | server.py:166 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2024-01-18 11:22:33,139 | server.py:218 | fit_round 3: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:22:54,870 | server.py:232 | fit_round 3 received 13 results and 0 failures
INFO flwr 2024-01-18 11:22:59,674 | server.py:119 | fit progress: (3, 2.2631728843971444, {'accuracy': 0.1927}, 93.1089934753254)
INFO flwr 2024-01-18 11:22:59,674 | server.py:166 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2024-01-18 11:22:59,676 | server.py:218 | fit_round 4: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:23:21,283 | server.py:232 | fit_round 4 received 13 results and 0 failures
INFO flwr 2024-01-18 11:23:26,081 | server.py:119 | fit progress: (4, 2.2431480601146414, {'accuracy': 0.1978}, 119.51635874714702)
INFO flwr 2024-01-18 11:23:26,082 | server.py:166 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2024-01-18 11:23:26,084 | server.py:218 | fit_round 5: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:23:47,701 | server.py:232 | fit_round 5 received 13 results and 0 failures
INFO flwr 2024-01-18 11:23:52,493 | server.py:119 | fit progress: (5, 2.22101862960064, {'accuracy': 0.22}, 145.9279423383996)
INFO flwr 2024-01-18 11:23:52,493 | server.py:166 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2024-01-18 11:23:52,495 | server.py:218 | fit_round 6: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:24:14,061 | server.py:232 | fit_round 6 received 13 results and 0 failures
INFO flwr 2024-01-18 11:24:18,856 | server.py:119 | fit progress: (6, 2.1925642726349657, {'accuracy': 0.2667}, 172.291475801263)
INFO flwr 2024-01-18 11:24:18,857 | server.py:166 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2024-01-18 11:24:18,859 | server.py:218 | fit_round 7: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:24:40,577 | server.py:232 | fit_round 7 received 13 results and 0 failures
INFO flwr 2024-01-18 11:24:45,381 | server.py:119 | fit progress: (7, 2.155776727745486, {'accuracy': 0.3057}, 198.81590809999034)
INFO flwr 2024-01-18 11:24:45,381 | server.py:166 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2024-01-18 11:24:45,383 | server.py:218 | fit_round 8: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:25:06,970 | server.py:232 | fit_round 8 received 13 results and 0 failures
INFO flwr 2024-01-18 11:25:11,776 | server.py:119 | fit progress: (8, 2.1110939102976656, {'accuracy': 0.3256}, 225.21073618717492)
INFO flwr 2024-01-18 11:25:11,776 | server.py:166 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2024-01-18 11:25:11,779 | server.py:218 | fit_round 9: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:25:34,413 | server.py:232 | fit_round 9 received 13 results and 0 failures
INFO flwr 2024-01-18 11:25:39,225 | server.py:119 | fit progress: (9, 2.060964001347239, {'accuracy': 0.3374}, 252.65978970797732)
INFO flwr 2024-01-18 11:25:39,225 | server.py:166 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2024-01-18 11:25:39,227 | server.py:218 | fit_round 10: strategy sampled 14 clients (out of 14)
DEBUG flwr 2024-01-18 11:26:00,927 | server.py:232 | fit_round 10 received 13 results and 1 failures
INFO flwr 2024-01-18 11:26:05,711 | server.py:119 | fit progress: (10, 2.0086349052262142, {'accuracy': 0.3503}, 279.1464725602418)
INFO flwr 2024-01-18 11:26:05,712 | server.py:166 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2024-01-18 11:26:05,714 | server.py:218 | fit_round 11: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:26:27,454 | server.py:232 | fit_round 11 received 13 results and 0 failures
INFO flwr 2024-01-18 11:26:32,244 | server.py:119 | fit progress: (11, 1.9566391216964352, {'accuracy': 0.3777}, 305.6792769781314)
INFO flwr 2024-01-18 11:26:32,244 | server.py:166 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2024-01-18 11:26:32,247 | server.py:218 | fit_round 12: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:26:53,858 | server.py:232 | fit_round 12 received 13 results and 0 failures
INFO flwr 2024-01-18 11:26:58,639 | server.py:119 | fit progress: (12, 1.9064998863881393, {'accuracy': 0.4036}, 332.0736845363863)
INFO flwr 2024-01-18 11:26:58,639 | server.py:166 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2024-01-18 11:26:58,642 | server.py:218 | fit_round 13: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:27:20,302 | server.py:232 | fit_round 13 received 13 results and 0 failures
INFO flwr 2024-01-18 11:27:25,073 | server.py:119 | fit progress: (13, 1.8589341373557817, {'accuracy': 0.4206}, 358.5077221910469)
INFO flwr 2024-01-18 11:27:25,073 | server.py:166 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2024-01-18 11:27:25,075 | server.py:218 | fit_round 14: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:27:46,946 | server.py:232 | fit_round 14 received 13 results and 0 failures
INFO flwr 2024-01-18 11:27:51,727 | server.py:119 | fit progress: (14, 1.8141524903883168, {'accuracy': 0.433}, 385.161745517049)
INFO flwr 2024-01-18 11:27:51,727 | server.py:166 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2024-01-18 11:27:51,729 | server.py:218 | fit_round 15: strategy sampled 14 clients (out of 14)
DEBUG flwr 2024-01-18 11:28:13,459 | server.py:232 | fit_round 15 received 13 results and 1 failures
INFO flwr 2024-01-18 11:28:18,194 | server.py:119 | fit progress: (15, 1.77214944194642, {'accuracy': 0.4422}, 411.6296005952172)
INFO flwr 2024-01-18 11:28:18,195 | server.py:166 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2024-01-18 11:28:18,197 | server.py:218 | fit_round 16: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:28:39,830 | server.py:232 | fit_round 16 received 13 results and 0 failures
INFO flwr 2024-01-18 11:28:44,565 | server.py:119 | fit progress: (16, 1.7327480693180164, {'accuracy': 0.4513}, 437.99970754329115)
INFO flwr 2024-01-18 11:28:44,565 | server.py:166 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2024-01-18 11:28:44,567 | server.py:218 | fit_round 17: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:29:06,270 | server.py:232 | fit_round 17 received 13 results and 0 failures
INFO flwr 2024-01-18 11:29:11,019 | server.py:119 | fit progress: (17, 1.6957270624258762, {'accuracy': 0.46}, 464.45429474441335)
INFO flwr 2024-01-18 11:29:11,019 | server.py:166 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2024-01-18 11:29:11,021 | server.py:218 | fit_round 18: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:29:32,663 | server.py:232 | fit_round 18 received 13 results and 0 failures
INFO flwr 2024-01-18 11:29:37,552 | server.py:119 | fit progress: (18, 1.660918855949779, {'accuracy': 0.4658}, 490.98743941122666)
INFO flwr 2024-01-18 11:29:37,553 | server.py:166 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2024-01-18 11:29:37,555 | server.py:218 | fit_round 19: strategy sampled 13 clients (out of 13)
DEBUG flwr 2024-01-18 11:29:40,678 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:29:40,882 | connection.py:113 | gRPC channel closed
booting up client 2
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {grpc_message:"ping timeout", grpc_status:14, created_time:"2024-01-18T11:29:40.678227969+01:00"}"
>
DEBUG flwr 2024-01-18 11:29:41,464 | connection.py:39 | ChannelConnectivity.IDLE
srun: error: awi22: task 2: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9232943.1
slurmstepd: error: *** STEP 9232943.1 ON awi22 CANCELLED AT 2024-01-18T11:29:41 ***
slurmstepd: error: common_file_write_content: unable to open '/sys/fs/cgroup/freezer/slurm/uid_618619/job_9232943/step_1/freezer.state' for writing: Permission denied
srun: error: awi22: tasks 0-1,3-9: Terminated
srun: Force Terminated StepId=9232943.1
