INFO flwr 2023-12-20 16:22:44,589 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2023-12-20 16:22:44,750 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2023-12-20 16:22:44,750 | server.py:86 | Initializing global parameters
INFO flwr 2023-12-20 16:22:44,751 | server.py:273 | Requesting initial parameters from one random client
server booted up. starting clients...
INFO flwr 2023-12-20 16:23:20,542 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-12-20 16:23:20,543 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-12-20 16:23:21,471 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-20 16:23:21,478 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:21,478 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-20 16:23:21,484 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-20 16:23:21,510 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-20 16:23:21,514 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:21,515 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-20 16:23:21,518 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-20 16:23:21,554 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2023-12-20 16:23:21,555 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2023-12-20 16:23:21,556 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-20 16:23:21,559 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:21,559 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-20 16:23:21,560 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:21,560 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-20 16:23:21,563 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-12-20 16:23:21,563 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-12-20 16:23:21,563 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:21,563 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-20 16:23:21,567 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-20 16:23:21,570 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-20 16:23:21,573 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:21,573 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-20 16:23:21,577 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-20 16:23:21,581 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2023-12-20 16:23:21,583 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2023-12-20 16:23:21,585 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-20 16:23:21,586 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:21,587 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-20 16:23:21,587 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:21,589 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-12-20 16:23:21,589 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2023-12-20 16:23:21,590 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-20 16:23:21,595 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-12-20 16:23:21,623 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:21,624 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-20 16:23:21,626 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-12-20 16:23:21,629 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:21,630 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-20 16:23:21,633 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-12-20 16:23:22,999 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:22,999 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:22,999 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-20 16:23:22,999 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 48, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-12-20T16:23:22.998019326+01:00", grpc_status:14, grpc_message:"Socket closed"}"
>
DEBUG flwr 2023-12-20 16:23:23,201 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 48, in <module>
DEBUG flwr 2023-12-20 16:23:23,203 | connection.py:113 | gRPC channel closed
DEBUG flwr 2023-12-20 16:23:23,203 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
booting up client 0
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 48, in <module>
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 48, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-12-20T16:23:22.997966698+01:00", grpc_status:14, grpc_message:"Socket closed"}"
>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Socket closed", grpc_status:14, created_time:"2023-12-20T16:23:22.998043945+01:00"}"
>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Socket closed", grpc_status:14, created_time:"2023-12-20T16:23:22.998044112+01:00"}"
>
srun: error: awi23: task 5: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9203976.1
slurmstepd: error: *** STEP 9203976.1 ON awi23 CANCELLED AT 2023-12-20T16:23:23 ***
INFO flwr 2023-12-20 16:23:23,673 | server.py:91 | initial parameters (loss, other metrics): 2.302488159060478, {'accuracy': 0.0995}
INFO flwr 2023-12-20 16:23:23,673 | server.py:101 | FL starting
slurmstepd: error: common_file_write_content: unable to open '/sys/fs/cgroup/freezer/slurm/uid_618619/job_9203976/step_1/freezer.state' for writing: Permission denied
srun: error: awi23: tasks 0-4,6-9: Terminated
srun: Force Terminated StepId=9203976.1
