INFO flwr 2024-01-17 15:24:06,171 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2024-01-17 15:24:06,210 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2024-01-17 15:24:06,210 | server.py:86 | Initializing global parameters
INFO flwr 2024-01-17 15:24:06,210 | server.py:269 | Using initial parameters provided by strategy
INFO flwr 2024-01-17 15:24:06,210 | server.py:88 | Evaluating initial parameters
server booted up. starting clients...
INFO flwr 2024-01-17 15:24:07,350 | server.py:91 | initial parameters (loss, other metrics): 2.303199114156204, {'accuracy': 0.1009}
INFO flwr 2024-01-17 15:24:07,350 | server.py:101 | FL starting
INFO flwr 2024-01-17 15:24:27,335 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:27,337 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:27,337 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:27,341 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:27,346 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:27,349 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:27,349 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:27,353 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:27,354 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:27,356 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:27,356 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:27,359 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:27,380 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:27,382 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:27,382 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:27,386 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:27,692 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:27,694 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:27,694 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2024-01-17 15:24:27,697 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:27,698 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 15:24:27,698 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:27,698 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:27,702 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:27,723 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:27,748 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:27,748 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:27,752 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:27,775 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:27,799 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:27,799 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:27,802 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:27,804 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:27,831 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:27,831 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:27,835 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:27,839 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:27,841 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:27,841 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:27,845 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 16:03:51,878 | connection.py:113 | gRPC channel closed
DEBUG flwr 2024-01-17 16:03:51,878 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 16:03:51,879 | app.py:185 | Disconnect and shut down
INFO flwr 2024-01-17 16:03:51,879 | app.py:185 | Disconnect and shut down
booting up client 0
booting up client 0
DEBUG flwr 2024-01-17 16:07:26,594 | connection.py:113 | gRPC channel closed
DEBUG flwr 2024-01-17 16:07:26,594 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 16:07:26,594 | app.py:185 | Disconnect and shut down
INFO flwr 2024-01-17 16:07:26,594 | app.py:185 | Disconnect and shut down
DEBUG flwr 2024-01-17 16:07:26,594 | connection.py:113 | gRPC channel closed
booting up client 0
DEBUG flwr 2024-01-17 16:07:26,594 | connection.py:113 | gRPC channel closed
booting up client 0
INFO flwr 2024-01-17 16:07:26,594 | app.py:185 | Disconnect and shut down
INFO flwr 2024-01-17 16:07:26,595 | app.py:185 | Disconnect and shut down
booting up client 0
booting up client 0
DEBUG flwr 2024-01-17 19:22:12,474 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 19:22:12,677 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-01-17T19:22:12.473627961+01:00", grpc_status:14, grpc_message:"Socket closed"}"
>
srun: error: 3dgi2: task 7: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9231391.1
slurmstepd: error: *** STEP 9231391.1 ON 3dgi2 CANCELLED AT 2024-01-17T19:22:13 ***
slurmstepd: error: common_file_write_content: unable to open '/sys/fs/cgroup/freezer/slurm/uid_618619/job_9231391/step_1/freezer.state' for writing: Permission denied
srun: error: 3dgi2: tasks 1,6,9: Terminated
srun: Force Terminated StepId=9231391.1
